//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class Global
{
	//不同平台下StreamingAssets的路径是不同的，这里需要注意一下。
	public static readonly string AssetBundleRootPath =
	#if UNITY_ANDROID
		"jar:file://" + Application.dataPath + "!/assets/";
	#elif UNITY_IPHONE
		Application.dataPath + "/Raw/";
	#elif UNITY_STANDALONE_WIN || UNITY_EDITOR
		"file://" + Application.dataPath + "/StreamingAssets/";
	#else
		string.Empty;
	#endif

	public const string SoundRootPath = "sound/";

	public static Camera mainCamera;
	public static Transform MainCameraTrans;

	public static Vector2 MoveHandlerVec = Vector2.zero;

	public Global ()
	{
	}
}

