//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
public class CommandConsts
{
	public const int CommandConsts_OnCellEnter = 30001;
	public const int CommandConsts_OnCellExit= 30002;
    public const int CommandConsts_OnCellClick = 30003;
    /**更新成员列表*/
    public const int CommandConsts_UpdateMemberList = 30003;

	/**激活操作控制器*/
	public const int CommandConsts_ActiveOperationController = 20001;
	/**进入区域*/
	public const int CommandConsts_EnterArea = 20002;
	public const int CommandConsts_ExitArea = 20003;

	public const int CommandConsts_PopUpWindow = 10000;
	public const int CommandConsts_RemoveWindow = 10001;
	public const int CommandConsts_DestroyWindow = 10002;

	public const int CommandConsts_UpdateLoadingProgress = 10011;
	public const int CommandConsts_UpdateLoadingBundleProgress = 10012;
	public const int CommandConsts_LoadBundleComplete = 10013;
	public const int CommandConsts_LoadAllBundlesComplete = 10014;

	public CommandConsts ()
	{

	}
}

