//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class WindowName
{
    public const string UnitOperationView = "UnitOperationView";

    public const string QuestPanelView = "QuestPanelView";

    public const string CrosshairView = "CrosshairView";

    public const string MathcBoxView = "MatchBoxView";

    public const string MenuView = "MenuView";

    public const string InstructionsView = "InstructionsView";
    /**加载界面视图*/
    public const string LoadingView = "LoadingView";

    public const string CharacterMoveControllerView = "CharacterMoveControllerView";
}

