//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class BattleUtils
{
    public static float getCellPosXByCol(int col)
    {
        return BattleGlobal.CellStartX + (0.5f + col) * BattleConsts.DefaultCellSize;
    }

    public static float getCellPosYByRow(int row)
    {
        return BattleGlobal.CellStartY + (0.5f + row) * BattleConsts.DefaultCellSize;
    }

    public static Vector3 getCellPosByLocation(int row, int col)
    {
        return new Vector3(getCellPosXByCol(col), getCellPosYByRow(row), 0);
    }
}