DAMAGE_REASON_ATTACK = 1;
DAMAGE_REASON_COUNTER_ATTACK = 2;
DAMAGE_REASON_SPELL = 3;
DAMAGE_REASON_BUFF = 4;

CODE_CHECK_BPOINT_COST_BY_ATTACK = 1;
CODE_SELECT_ATTACK_TARGET = 2;
CODE_PRE_DAMAGE = 3;
CODE_DAMAGE = 4;
CODE_CAlC_DAMAGE_ATTACKER = 5;
CODE_CAlC_DAMAGE_VICTIM = 6;
CODE_TAKE_DAMAGE = 7;

EFFECT_TYPE_ACTIVATE = 0x01;
EFFECT_TYPE_TRIGGER = 0X02;

PROPERTY_ATTACK_ATTACKER = 3000;
PROPERTY_ATTACK_DEFENDER = 3001;
PROPERTY_MIN_ATTACK_DIS_EXTRA = 3002;
PROPERTY_MAX_ATTACK_DIS_EXTRA = 3003;
PROPERTY_PHYSICAL_DAMAGE = 3010;
PROPERTY_PHYSICAL_DAMAGE_BASE_OUTGOING = 3011;
PROPERTY_PHYSICAL_DAMAGE_PERCENTAGE = 3012;
PROPERTY_PHYSICAL_DAMAGE_EXTRA_OUTGOING = 3013;
PROPERTY_SPELL_DAMAGE = 3020;
PROPERTY_SPELL_DAMAGE_BASE_OUTGOING = 3021;
PROPERTY_SPELL_DAMAGE_PERCENTAGE = 3022;
PROPERTY_SPELL_DAMAGE_EXTRA_OUTGOING = 3023;
PROPERTY_TOTAL_DAMAGE_REDUCTION = 3040;
PROPERTY_PHYSICAL_DAMAGE_REDUCTION = 3041;
PROPERTY_SPELL_DAMAGE_REDUCTION = 3042;
PROPERTY_DAMAGE_ATTACKER = 3050;
PROPERTY_DAMAGE_VICTIM = 3051;
PROPERTY_DAMAGE_REASON = 3060;
PROPERTY_HP_REMOVAL = 3070;
PROPERTY_CALC_PHYSICAL_DAMAGE = 3080;
PROPERTY_CALC_SPELL_DAMAGE = 3081;
PROPERTY_CALC_HP_REMOVAL = 3082;

PROPERTY_TRANSLATE_TARGET = 3100;
PROPERTY_TRANSLATE_REASON = 3101;
PROPERTY_TRANSLATE_ORIGINAL_ROW = 3110;
PROPERTY_TRANSLATE_ORIGINAL_COL = 3111;
PROPERTY_TRANSLATE_OFFSET_ROW = 3120;
PROPERTY_TRANSLATE_OFFSET_COL = 3121;
PROPERTY_TRANSLATE_TARGET_ROW = 3130;
PROPERTY_TRANSLATE_TARGET_COL = 3131;
PROPERTY_TRANSLATE_PATH = 3140;